env:
  browser: true
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "prefer-const": "error",
  "no-var": "error",
  "object-curly-spacing": [1, "always"],
}
